-- Stap 1: Tabel aanmaken
create table if not exists clients (
  id uuid default gen_random_uuid() primary key,
  slug text not null unique,
  naam text not null,
  created_at timestamptz default now()
);

alter table clients enable row level security;
create policy "public read" on clients for select using (true);

-- Stap 2: Bestaande 85 clients importeren
insert into clients (slug, naam) values
  ('aanlegservice-nh', 'Aanlegservice Nh'),
  ('ariebouw', 'Ariebouw'),
  ('bb', 'Bb'),
  ('berendsz-dak', 'Berendsz Dak'),
  ('bobs-tegels', 'Bobs Tegels'),
  ('booby-schoon-raam', 'Booby Schoon Raam'),
  ('bouwbedrijf-de-vries', 'Bouwbedrijf De Vries'),
  ('charvat-tuinen', 'Charvat Tuinen'),
  ('dakappie', 'Dakappie'),
  ('dakdekker-brams', 'Dakdekker Brams'),
  ('dakdekker-de-dakpan', 'Dakdekker De Dakpan'),
  ('dakdekker-fsom', 'Dakdekker Fsom'),
  ('dakdekker-leersum-bv', 'Dakdekker Leersum Bv'),
  ('dakdekker-max', 'Dakdekker Max'),
  ('dakdekker-maxcs', 'Dakdekker Maxcs'),
  ('dakdekker-max-veer-bv', 'Dakdekker Max Veer Bv'),
  ('dakdekker-panniee', 'Dakdekker Panniee'),
  ('dakdekkers-max-en-marc', 'Dakdekkers Max En Marc'),
  ('dakdekkert-max', 'Dakdekkert Max'),
  ('dakdekker-van-de-berg-bv', 'Dakdekker Van De Berg Bv'),
  ('dakjan', 'Dakjan'),
  ('dakkia-pang', 'Dakkia Pang'),
  ('dakkie-pan', 'Dakkie Pan'),
  ('dakman-wybe', 'Dakman Wybe'),
  ('dakmax', 'Dakmax'),
  ('dakmaxman', 'Dakmaxman'),
  ('de-baksteen', 'De Baksteen'),
  ('de-grote-dakdekker', 'De Grote Dakdekker'),
  ('de-lekkageman', 'De Lekkageman'),
  ('de-nieuwe-dakker', 'De Nieuwe Dakker'),
  ('dh-woning-onderhoud-', 'Dh Woning Onderhoud '),
  ('elektricien24', 'Elektricien24'),
  ('elektricien-de-lamp', 'Elektricien De Lamp'),
  ('elektricien-het-zonnepaneel', 'Elektricien Het Zonnepaneel'),
  ('elise-de-schilder', 'Elise De Schilder'),
  ('fqfr', 'Fqfr'),
  ('g', 'G'),
  ('hakpansz', 'Hakpansz'),
  ('hans-bouwt-het', 'Hans Bouwt Het'),
  ('haris-dakkie', 'Haris Dakkie'),
  ('harriaman-dak', 'Harriaman Dak'),
  ('harri-daksz', 'Harri Daksz'),
  ('hdjjd', 'Hdjjd'),
  ('het-dakpand', 'Het Dakpand'),
  ('het-dakpantje', 'Het Dakpantje'),
  ('het-dak-van-olaf', 'Het Dak Van Olaf'),
  ('hier-', 'Hier '),
  ('hoiashao', 'Hoiashao'),
  ('hoveniersbedrijf-jerry', 'Hoveniersbedrijf Jerry'),
  ('ilse-de-dakdekker', 'Ilse De Dakdekker'),
  ('installatiepaal', 'Installatiepaal'),
  ('j', 'J'),
  ('jaccodesigntegelwerken-', 'Jaccodesigntegelwerken '),
  ('jan-de-man', 'Jan De Man'),
  ('jansens-loodgieyer', 'Jansens Loodgieyer'),
  ('jappie-dakpan', 'Jappie Dakpan'),
  ('jari-verf', 'Jari Verf'),
  ('launchdak-max', 'Launchdak Max'),
  ('Loodgieter Jan', 'Loodgieter Jan'),
  ('loodgieter-petje', 'Loodgieter Petje'),
  ('marc', 'Marc'),
  ('mersch-dakbedekking', 'Mersch Dakbedekking'),
  ('mijndak', 'Mijndak'),
  ('nieuwe-daken-bv', 'Nieuwe Daken Bv'),
  ('nog-een-dakpan', 'Nog Een Dakpan'),
  ('pauls-dakpan', 'Pauls Dakpan'),
  ('peter-wasbak', 'Peter Wasbak'),
  ('piet', 'Piet'),
  ('puks-dakpan', 'Puks Dakpan'),
  ('schilderkwast-bv', 'Schilderkwast Bv'),
  ('schildersbedrijf-veer', 'Schildersbedrijf Veer'),
  ('tegi-tegel', 'Tegi Tegel'),
  ('test', 'Test'),
  ('timdakpan', 'Timdakpan'),
  ('timmerbedrijf-jerry', 'Timmerbedrijf Jerry'),
  ('timmerman-adre', 'Timmerman Adre'),
  ('timmerman-de-hamer', 'Timmerman De Hamer'),
  ('timmer-timmerman', 'Timmer Timmerman'),
  ('tim-timmer', 'Tim Timmer'),
  ('tomb-op-t-dak', 'Tomb Op T Dak'),
  ('tom-plant', 'Tom Plant'),
  ('veer-aannemers-bv', 'Veer Aannemers Bv'),
  ('veer-dakdekkers', 'Veer Dakdekkers'),
  ('wybe-installatie', 'Wybe Installatie'),
  ('zed-de-dakdekker', 'Zed De Dakdekker')
on conflict (slug) do nothing;
